### ISSUE TITLE
[UT-255] As a user I want to add or edit an experience to my profile

### ISSUE THREAD

**Issue by gregory-latinier** [utopian-io/v2.utopian.io#169]
Add experiences to a profile (pretty much like linked in)

NB: the design doesn't match what has currently been done for the edit profile module
Follow the existing card example.

*Acceptance criteria*
* Add plus icon on the right side of the title 'Work experiences'  (blue round + icon), it opens the form just above the work experience list
* The add/edit form is hidden by default unless you click on the + or edit button 
* toMonth and toYear are required if current is set to false
* add a 3 verticals dots button on existing experiences to either delete or edit them
* edit opens and fill the form with the data
* delete display a confirm dialog
* Display the text : "tell us about your different jobs and projects" if no experiences have been added
* Don't add the helper texts, they don't provide additional information

Design

![image](https://user-images.githubusercontent.com/13222767/48843813-819a8700-ed98-11e8-9a48-0342438aa1e4.png)

UML
experiences subdocument of the user model
* jobTitle: String required
* company: String required
* location: String
* fromMonth: integer required
* fromYear: integer required
* toMonth: integer
* toYear: integer
* current: boolean default false
* description: String (500)

**Comment by eastmaels** [comment]
TODO:
- [ ] submit new work experience using form
- [ ] list existing experiences as qcards
- [ ] display from when editing a work experience
- [ ] submit edit form
- [ ] display confirmation dialog when deleting a work experience

**Comment by eastmaels** [comment]
PR Review TODOs:

- [ ] move the add icon on the right side of the title
- [ ] use just a + icon without the circle
- [ ] remove double shadow
- [ ] Sort the experiences from the most recent to the oldest
- [ ] I shouldn't be able to set a future date
- [ ] check that the from date is before the end date
- [ ] scroll the user back to the form when editing an experience
- [ ] Use save instead of create
- [ ] Reset error state when creating a second experience

**Comment by eastmaels** [comment]
- [ ] start from date input format ()
- [ ] return q-datetime input design from minimal to default (The date design has changed. I can't quickly go to a year.)
- [ ] add some margin q-mb-md to work experience cards
- [ ] add a cancel button, secondary color. empties and hide the form.
- [ ] Use dot as a separator
- [ ] add icons to dropdown - pencil for edit, trash can for delete
