### ISSUE TITLE
[UT-256] As a user I want to add or edit a study to my profile

### ISSUE THREAD

**Issue by gregory-latinier** [utopian-io/v2.utopian.io#170]
Do the same as the UT-255 (#169 ).

*Acceptance criteria*
* A plus icon opens the form below the title 'Education' (blue round + icon)
* add a 3 verticals dots button on existing studies to either delete or edit them
* edit opens and fill the form with the data
* delete display a confirm dialog

Design

![image](https://user-images.githubusercontent.com/13222767/48844179-64b28380-ed99-11e8-9e37-666cd077a417.png)

UML

study subdocument:
* school: string required
* diploma: string
* domain: string
* grade: string
* fromYear: integer
* toYear: integer
* description: string (500)

**Comment by eastmaels** [comment]
Hi @gregory-latinier I'd like to take this task if it's still available.

**Comment by AneilPatel05** [comment]
I would like to take this task. @gregory-latinier

**Comment by gregory-latinier** [comment]
This task is already assigned...
