### ISSUE TITLE
[UT-415] As a user I want to add a project to the article

### ISSUE THREAD

**Issue by gregory-latinier** [utopian-io/v2.utopian.io#199]
*Acceptance criteria*

* The search project will search among all utopian's projects that are not blacklisted. The search will use the project name fields. Like in github if the search contains a '/' the left part will be the owner and the search will only display projects of the owner.
* The search will sort the result by displaying the projects where he's an owner first, then a collaborator, then the rest of the search.
* Ex: 'utopian' will search for the projects where the name starts with 'utopian'
* Ex: 'utopian/v2' will search for the utopian's user projects only that starts with v2
* Limit the search results to 10 projects
* If the selected project doesn’t allow external contributions and the user is not the project owner or in the collaborator’s list with the articles roles. Display an error notice with the message ‘You don't have the right to contribute to this project. Please consider forking the project.’
* If the route contains the project query parameter, fill the project field, check for the project detail page, write an article button. Don't forget to do the controls.

*Design*
![image](https://user-images.githubusercontent.com/13222767/49215422-0e60c880-f3c9-11e8-9879-7e36267cdc1a.png)

*UML*
![image](https://user-images.githubusercontent.com/13222767/49215478-305a4b00-f3c9-11e8-8191-f85c503c6374.png)

**Comment by AneilPatel05** [comment]
I am interested in this task.
