### ISSUE TITLE
Beta server

### ISSUE THREAD

**Issue by abitrolly** [utopian-io/v2.utopian.io#27]
https://v2.utopian.io is not there. Is there other server to test new application?

**Comment by icaroharry** [comment]
Hi @abitrolly. This is not public yet. We're planning a release to be done soon. More info on steemit.com/@utopian-io

**Comment by abitrolly** [comment]
In the meanwhile is there a chance to see simple fixes merged for the current public website? https://github.com/utopian-io/join.utopian.io/pull/100
